baseURL = "https://blog.aryang.dev"

theme = 'hugo-bearblog'

title = "note-to-self"
author = "Audrey Yang"
copyright = "Copyright © 2025, Audrey Yang."
languageCode = "en-US"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Learning in public"
  favicon = "static/images/favicon.png"
  title = "Audrey's Note To Self"
  hideMadeWithLine = true
  dateFormat = "Jan. 2, 2006"

[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true